# Use root/example as user/password credentials
version: '3.1'

services:

  bookipy:
    build: .
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
#      - FLASK_RUN_HOST 0.0.0.0
    ports:
      - 5000:5000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/